import fs from 'fs/promises'
import path from 'path'

import { ThemeToken } from '../types.js'
import { WriterAdapter } from './adapter.js'

export class DocsWriter implements WriterAdapter {
  async write(
    theme: ThemeToken,
    outputDir: string,
    options?: { title?: string }
  ): Promise<string[]> {
    const filesWritten: string[] = []
    await fs.mkdir(outputDir, { recursive: true })

    // 1. Generate Markdown Documentation
    const mdContent = this.generateMarkdown(theme, options?.title || 'Design Tokens')
    const mdPath = path.join(outputDir, 'tokens.md')
    await fs.writeFile(mdPath, mdContent)
    filesWritten.push(mdPath)

    // 2. Generate JSON (Raw Data for custom docs sites)
    const jsonPath = path.join(outputDir, 'tokens.json')
    await fs.writeFile(jsonPath, JSON.stringify(theme, null, 2))
    filesWritten.push(jsonPath)

    return filesWritten
  }

  private generateMarkdown(theme: ThemeToken, title: string): string {
    let md = `# ${title}\n\n`
    md += `> Generated by ForgeKit Chakra Figma MCP\n\n`

    // Colors
    md += `## Colors\n\n`

    // Primitives
    if (Object.keys(theme.colors).length > 0) {
      md += `### Primitives\n\n`
      md += `| Name | Value | Preview |\n`
      md += `|------|-------|---------|\n`

      const flatten = (obj: any, prefix: string) => {
        for (const [key, value] of Object.entries(obj)) {
          if (typeof value === 'string') {
            md += `| ${prefix}${key} | \`${value}\` | <div style="background:${value};width:20px;height:20px;border:1px solid #ddd;border-radius:4px;"></div> |\n`
          } else {
            flatten(value, `${prefix}${key}.`)
          }
        }
      }
      flatten(theme.colors, '')
      md += `\n`
    }

    // Semantic
    if (theme.semanticTokens?.colors && Object.keys(theme.semanticTokens.colors).length > 0) {
      md += `### Semantic Colors\n\n`
      md += `| Token | Light | Dark |\n`
      md += `|-------|-------|------|\n`

      const flattenSemantic = (obj: any, prefix: string) => {
        for (const [key, value] of Object.entries(obj)) {
          if (typeof value === 'object' && (value as any)._light) {
            const light = (value as any)._light
            const dark = (value as any)._dark || light
            md += `| ${prefix}${key} | <div style="display:flex;align-items:center;gap:8px;"><div style="background:${light};width:16px;height:16px;border:1px solid #ddd;border-radius:4px;"></div> \`${light}\`</div> | <div style="display:flex;align-items:center;gap:8px;"><div style="background:${dark};width:16px;height:16px;border:1px solid #ddd;border-radius:4px;"></div> \`${dark}\`</div> |\n`
          } else if (typeof value === 'object') {
            flattenSemantic(value, `${prefix}${key}.`)
          }
        }
      }
      flattenSemantic(theme.semanticTokens.colors, '')
      md += `\n`
    }

    // Spacing
    if (Object.keys(theme.space).length > 0) {
      md += `## Spacing\n\n`
      md += `| Name | Value | Pixels |\n`
      md += `|------|-------|--------|\n`
      for (const [key, value] of Object.entries(theme.space)) {
        md += `| ${key} | \`${value}\` | ${value} |\n`
      }
      md += `\n`
    }

    // Radii
    if (Object.keys(theme.radii).length > 0) {
      md += `## Radii\n\n`
      md += `| Name | Value |\n`
      md += `|------|-------|\n`
      for (const [key, value] of Object.entries(theme.radii)) {
        md += `| ${key} | \`${value}\` |\n`
      }
      md += `\n`
    }

    return md
  }
}
